# Generated by Django 4.0.6 on 2023-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, to='api.commentproduct'),
        ),
    ]
