# Generated by Django 4.0.6 on 2023-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AlterField(
            model_name='product',
            name='isAmazing',
            field=models.BooleanField(default=False),
        ),
    ]
